version: '3'

services:
  caddy:
    container_name: caddy
    image: caddy:2.6.3
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - services-network


volumes:
  caddy_data:
  caddy_config:

networks:
  services-network:
    name: services-network
    external: true