version: '3'

services:
  pocketbase:
    container_name: pocketbase
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - pb_data:/pb/pb_data
    networks:
      - services-network

volumes:
  pb_data:

networks:
  services-network:
    name: services-network
    external: true